-- ============================================
-- QUERIES SQL - GED FACULDADE NOVA ROMA
-- Sistema Completo com Usuários, Colaboradores
-- Documentos, RH e Financeiro
-- ============================================

-- Execute no SQL Editor do Supabase em ordem numérica

-- ============================================
-- A. SETUP INICIAL (EXTENSÕES)
-- ============================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS must_change_password boolean DEFAULT false;

-- ============================================
-- B. USUÁRIOS DO SISTEMA
-- ============================================

-- B.1 - Administrador (acesso a tudo)
INSERT INTO usuarios (nome, username, senha, acesso)
VALUES (
  'Administrador GED',
  'admin@novaroma.edu.br',
  encode(digest('Nova@123!','sha256'), 'hex'),
  'ambos'
)
ON CONFLICT (username) DO UPDATE
SET senha = excluded.senha,
    nome = excluded.nome,
    acesso = excluded.acesso;

-- B.2 - Usuários de exemplo removidos
-- As contas de teste foram removidas para deixar o sistema apenas com o administrador
-- inicial. Crie novas contas pela página de Gestão de Usuários.

-- Verificar usuários criados
SELECT id, nome, username, acesso, created_at 
FROM usuarios 
ORDER BY created_at DESC;

-- ============================================
-- C. COLABORADORES RH
-- ============================================

-- Colaboradores de exemplo removidos para manter o banco limpo.
-- Crie colaboradores diretamente pelo sistema de RH.

-- C.2 - Verificar colaboradores inseridos
SELECT id, nome, funcao, situacao, matricula, email_corporativo 
FROM colaboradores 
ORDER BY nome;

-- ============================================
-- D. PASTAS DE DOCUMENTOS RH
-- ============================================

-- D.1 - Criar pastas para cada colaborador ativo
INSERT INTO pastas_documentos (colaborador_id, categoria, nome_arquivo)
SELECT 
  id,
  'Documentos Pessoais',
  'Documentos-Pessoais-' || nome || '.pdf'
FROM colaboradores
WHERE situacao = 'Ativo'
ON CONFLICT DO NOTHING;

-- D.2 - Adicionar mais documentos
INSERT INTO pastas_documentos (colaborador_id, categoria, nome_arquivo)
SELECT 
  id,
  'Contrato',
  'Contrato-Trabalho-' || nome || '.pdf'
FROM colaboradores
WHERE situacao = 'Ativo'
ON CONFLICT DO NOTHING;

-- D.3 - Verificar pastas criadas
SELECT pd.id, c.nome, pd.categoria, pd.nome_arquivo, pd.data_upload
FROM pastas_documentos pd
JOIN colaboradores c ON pd.colaborador_id = c.id
ORDER BY c.nome;

-- ============================================
-- E. DOCUMENTOS FINANCEIROS
-- ============================================

-- E.0 - Tabela de documentos financeiros
CREATE TABLE IF NOT EXISTS documentos (
  id bigint generated by default as identity primary key,
  tipo_doc text not null,
  setor text not null,
  identificador text not null unique,
  valor numeric(12,2) default 0,
  tipo_financeiro text not null check (tipo_financeiro in ('Receita', 'Despesa')),
  data_envio date default current_date,
  status_assinatura text default 'Pendente Assinatura',
  tags text default '',
  numero_nf text default '',
  created_at timestamptz default now()
);

-- E.1 - Notas Fiscais (Despesa)
INSERT INTO documentos (
  tipo_doc, setor, identificador, valor, tipo_financeiro, 
  data_envio, status_assinatura, tags, numero_nf
)
VALUES
  (
    'Nota Fiscal',
    'Financeiro',
    'FIN-001',
    1500.00,
    'Despesa',
    CURRENT_DATE,
    'Pendente Assinatura',
    'fiscal,urgente',
    'NF-001234'
  ),
  (
    'Nota Fiscal',
    'Acadêmico',
    'ACA-001',
    2500.00,
    'Despesa',
    CURRENT_DATE,
    'Assinado & Arquivado',
    'fiscal',
    'NF-001235'
  ),
  (
    'Boleto/Recibo',
    'RH / DP',
    'RH-001',
    5000.00,
    'Despesa',
    CURRENT_DATE,
    'Pendente Assinatura',
    'financeiro',
    NULL
  )
ON CONFLICT (identificador) DO NOTHING;

-- E.2 - Verificar documentos
SELECT id, tipo_doc, setor, valor, tipo_financeiro, status_assinatura, created_at
FROM documentos
ORDER BY created_at DESC;

-- E.3 - Relatório de despesas por setor
SELECT 
  setor,
  COUNT(*) AS total_documentos,
  SUM(valor) AS valor_total,
  AVG(valor) AS valor_medio
FROM documentos
WHERE tipo_financeiro = 'Despesa'
GROUP BY setor
ORDER BY valor_total DESC;

-- ============================================
-- F. ÍNDICES DE PERFORMANCE
-- ============================================

CREATE INDEX IF NOT EXISTS idx_usuarios_username ON usuarios(username);
CREATE INDEX IF NOT EXISTS idx_usuarios_acesso ON usuarios(acesso);
CREATE INDEX IF NOT EXISTS idx_colaboradores_situacao ON colaboradores(situacao);
CREATE INDEX IF NOT EXISTS idx_colaboradores_matricula ON colaboradores(matricula);
CREATE INDEX IF NOT EXISTS idx_colaboradores_email ON colaboradores(email_corporativo);
CREATE INDEX IF NOT EXISTS idx_pastas_colaborador ON pastas_documentos(colaborador_id);
CREATE INDEX IF NOT EXISTS idx_pastas_categoria ON pastas_documentos(categoria);
CREATE INDEX IF NOT EXISTS idx_documentos_setor ON documentos(setor);
CREATE INDEX IF NOT EXISTS idx_documentos_status ON documentos(status_assinatura);
CREATE INDEX IF NOT EXISTS idx_documentos_tipo_financeiro ON documentos(tipo_financeiro);
CREATE INDEX IF NOT EXISTS idx_documentos_data ON documentos(data_envio);

-- ============================================
-- G. LIMPEZA E RESET (SE NECESSÁRIO)
-- ============================================

-- G.1 - Ver tudo que foi criado
SELECT 'Usuários' as tabela, COUNT(*) as quantidade FROM usuarios
UNION ALL
SELECT 'Colaboradores', COUNT(*) FROM colaboradores
UNION ALL
SELECT 'Pastas de Documentos', COUNT(*) FROM pastas_documentos
UNION ALL
SELECT 'Documentos', COUNT(*) FROM documentos;

-- G.2 - Deletar tudo (CUIDADO - USE APENAS SE NECESSÁRIO)
-- DELETE FROM documentos;
-- DELETE FROM pastas_documentos;
-- DELETE FROM colaboradores;
-- DELETE FROM usuarios;

-- ============================================
-- H. QUERIES ÚTEIS PARA O SISTEMA
-- ============================================

-- H.1 - Listar todos os usuários com permissões
SELECT 
  id,
  nome,
  username,
  acesso,
  CASE 
    WHEN acesso = 'ambos' THEN 'Acesso Completo'
    WHEN acesso = 'financeiro' THEN 'Apenas Financeiro'
    WHEN acesso = 'rh' THEN 'Apenas RH'
    ELSE 'Apenas Observação'
  END as permissao_descrita,
  created_at
FROM usuarios
ORDER BY nome;

-- H.2 - Colaboradores por departamento
SELECT 
  unidade,
  COUNT(*) as total,
  COUNT(CASE WHEN situacao = 'Ativo' THEN 1 END) as ativos,
  COUNT(CASE WHEN situacao = 'Inativo' THEN 1 END) as inativos,
  ROUND(AVG(remuneracao), 2) as salario_medio
FROM colaboradores
GROUP BY unidade
ORDER BY total DESC;

-- H.3 - Documentos com status pendente
SELECT 
  id,
  tipo_doc,
  setor,
  valor,
  data_envio,
  numero_nf,
  status_assinatura
FROM documentos
WHERE status_assinatura = 'Pendente Assinatura'
ORDER BY data_envio DESC;

-- H.4 - Resumo financeiro do mês
SELECT 
  DATE_TRUNC('month', data_envio)::DATE as mes,
  tipo_financeiro,
  COUNT(*) as documentos,
  ROUND(SUM(valor), 2) as valor_total
FROM documentos
WHERE DATE_TRUNC('month', data_envio) = DATE_TRUNC('month', CURRENT_DATE)
GROUP BY DATE_TRUNC('month', data_envio), tipo_financeiro
ORDER BY mes DESC;

-- H.5 - Próximos aniversariantes (RH)
SELECT 
  nome,
  data_nasc,
  EXTRACT(MONTH FROM data_nasc) as mes,
  EXTRACT(DAY FROM data_nasc) as dia,
  CASE 
    WHEN EXTRACT(MONTH FROM data_nasc) = EXTRACT(MONTH FROM CURRENT_DATE) THEN 'Este Mês'
    WHEN EXTRACT(MONTH FROM data_nasc) = EXTRACT(MONTH FROM CURRENT_DATE + INTERVAL '1 month') THEN 'Próximo Mês'
    ELSE 'Futuro'
  END as quando
FROM colaboradores
WHERE situacao = 'Ativo'
ORDER BY EXTRACT(MONTH FROM data_nasc), EXTRACT(DAY FROM data_nasc);

-- ============================================
-- CREDENCIAIS DE TESTE
-- ============================================

/*
USUÁRIOS CRIADOS:

1. Administrador (Acesso Completo)
   Email: admin@novaroma.edu.br
   Senha: Nova@123!
   Acesso: ambos (Financeiro + RH)

2. Gestor Financeiro
   Email: joao.financeiro@novaroma.edu.br
   Senha: Senha@123!
   Acesso: financeiro

3. Gestor RH
   Email: maria.rh@novaroma.edu.br
   Senha: Senha@123!
   Acesso: rh

4. Observador (Apenas Leitura)
   Email: pedro.observador@novaroma.edu.br
   Senha: Senha@123!
   Acesso: apenas-observador

5. Administrativo (Acesso Completo)
   Email: ana.admin@novaroma.edu.br
   Senha: Senha@123!
   Acesso: ambos
*/

-- ============================================
-- FIM DAS QUERIES
-- ============================================
