-- ============================================
-- SCHEMA SQL - GED Faculdade Nova Roma
-- Execute no SQL Editor do Supabase
-- ============================================

-- 1. USUÁRIOS
create table if not exists usuarios (
  id bigint generated by default as identity primary key,
  nome text not null,
  username text not null unique,
  senha text not null,
  acesso text not null check (acesso in ('financeiro', 'rh', 'ambos', 'apenas-observador')),
  must_change_password boolean default false,
  created_at timestamptz default now()
);

-- 2. COLABORADORES (RH)
create table if not exists colaboradores (
  id bigint generated by default as identity primary key,
  nome text not null,
  funcao text default '',
  situacao text default 'Ativo' check (situacao in ('Ativo', 'Inativo')),
  admissao date,
  demissao date,
  matricula text default '',
  localizacao text default '',
  unidade text default '',
  data_nasc date,
  remuneracao numeric(12,2) default 0,
  telefone text default '',
  rg text default '',
  cpf text default '',
  pis text default '',
  sexo text default '',
  pai_mae text default '',
  titulacao text default '',
  curso text default '',
  email_pessoal text default '',
  email_corporativo text default '',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. PASTAS DE DOCUMENTOS (RH)
create table if not exists pastas_documentos (
  id bigint generated by default as identity primary key,
  colaborador_id bigint not null references colaboradores(id) on delete cascade,
  categoria text not null,
  nome_arquivo text not null,
  tamanho text default '',
  data_upload date default current_date,
  status text default 'Enviado',
  tipo text default '',
  observacao text default '',
  created_at timestamptz default now()
);

-- 4. MOVIMENTAÇÕES RH
create table if not exists movimentacoes_rh (
  id bigint generated by default as identity primary key,
  colaborador_id bigint not null references colaboradores(id) on delete cascade,
  categoria text not null,
  nome_arquivo text not null,
  tamanho text default '',
  data_upload date default current_date,
  created_at timestamptz default now()
);

-- 5. CONTRATOS / DOCUMENTAÇÕES ENVIADAS
create table if not exists contratos (
  id bigint generated by default as identity primary key,
  colaborador_id bigint not null references colaboradores(id) on delete cascade,
  tipo text not null,
  nome_arquivo text not null,
  observacao text default '',
  destinatarios jsonb default '[]',
  status text default 'Pendente Assinatura',
  created_at timestamptz default now()
);

-- 6. DOCUMENTOS GED (Captura & Classificação)
create table if not exists documentos_ged (
  id bigint generated by default as identity primary key,
  tipo_documento text not null,
  setor text not null,
  cpf text default '',
  cnpj text default '',
  valor numeric(12,2) default 0,
  tipo_financeiro text default '' check (tipo_financeiro in ('', 'Receita', 'Despesa')),
  data_envio date default current_date,
  data_vencimento date,
  numero_nota text default '',
  tags text[] default '{}',
  codigo_siga text default '',
  data_validade date,
  lembrete_dias int default 0,
  email_assinante text default '',
  nome_arquivo text not null,
  url_arquivo text default '',
  status text default 'Pendente',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 7. TRANSAÇÕES FINANCEIRAS (Fluxo de Caixa)
create table if not exists transacoes_financeiras (
  id bigint generated by default as identity primary key,
  data date not null default current_date,
  descricao text not null,
  centro_custo text not null,
  tipo text not null check (tipo in ('Receita', 'Despesa')),
  valor numeric(12,2) not null default 0,
  created_at timestamptz default now()
);

-- 8. ANEXOS DE DOCUMENTOS GED
create table if not exists anexos_documentos (
  id bigint generated by default as identity primary key,
  documento_id bigint not null references documentos_ged(id) on delete cascade,
  nome_arquivo text not null,
  url_arquivo text not null,
  tamanho text default '',
  created_at timestamptz default now()
);

-- ============================================
-- ÍNDICES
-- ============================================
create index if not exists idx_pastas_colaborador on pastas_documentos(colaborador_id);
create index if not exists idx_movimentacoes_colaborador on movimentacoes_rh(colaborador_id);
create index if not exists idx_contratos_colaborador on contratos(colaborador_id);
create index if not exists idx_documentos_setor on documentos_ged(setor);
create index if not exists idx_documentos_tipo on documentos_ged(tipo_documento);
create index if not exists idx_transacoes_data on transacoes_financeiras(data);
create index if not exists idx_anexos_documento on anexos_documentos(documento_id);

-- ============================================
-- POLÍTICAS RLS (Row Level Security)
-- ============================================
alter table usuarios enable row level security;
alter table colaboradores enable row level security;
alter table pastas_documentos enable row level security;
alter table movimentacoes_rh enable row level security;
alter table contratos enable row level security;
alter table documentos_ged enable row level security;
alter table transacoes_financeiras enable row level security;
alter table anexos_documentos enable row level security;

-- Política: todos os usuários autenticados podem ler tudo
create policy "Leitura para todos autenticados" on usuarios
  for select using (auth.role() = 'authenticated');

create policy "Leitura para todos autenticados" on colaboradores
  for select using (auth.role() = 'authenticated');

create policy "Leitura para todos autenticados" on pastas_documentos
  for select using (auth.role() = 'authenticated');

create policy "Leitura para todos autenticados" on movimentacoes_rh
  for select using (auth.role() = 'authenticated');

create policy "Leitura para todos autenticados" on contratos
  for select using (auth.role() = 'authenticated');

create policy "Leitura para todos autenticados" on documentos_ged
  for select using (auth.role() = 'authenticated');

create policy "Leitura para todos autenticados" on transacoes_financeiras
  for select using (auth.role() = 'authenticated');

create policy "Leitura para todos autenticados" on anexos_documentos
  for select using (auth.role() = 'authenticated');

-- Política: admins podem inserir/editar/deletar
-- Policies: allow create/update/delete only when the acting user
-- has 'financeiro' or 'ambos' access in the `usuarios` table.
-- NOTE: PostgreSQL policy syntax uses `WITH CHECK` for INSERT and
-- `USING` for SELECT/UPDATE/DELETE. The original `with exists` was
-- invalid SQL (caused the syntax error). Adapt the subquery to your
-- auth linkage (e.g. join on auth.uid() or username) if needed.

create policy "Insert admin" on documentos_ged
  for insert with check (exists (select 1 from usuarios where acesso in ('financeiro', 'ambos')));

create policy "Update admin" on documentos_ged
  for update using (exists (select 1 from usuarios where acesso in ('financeiro', 'ambos')));

create policy "Delete admin" on documentos_ged
  for delete using (exists (select 1 from usuarios where acesso in ('financeiro', 'ambos')));

-- ============================================
-- FUNÇÕES ÚTEIS
-- ============================================

-- Inserir usuário admin padrão
-- insert into usuarios (nome, username, senha, acesso) values
--   ('Administrador', 'admin', 'admin123', 'ambos'),
--   ('Financeiro', 'financeiro', 'fin123', 'financeiro'),
--   ('RH', 'rh', 'rh123', 'rh'),
--   ('Observador', 'obs', 'obs123', 'apenas-observador');

-- Habilita pgcrypto para hashing (bcrypt via crypt/gen_salt)
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Função auxiliar: cria um usuário com hash bcrypt no banco
CREATE OR REPLACE FUNCTION create_user(
  p_nome text,
  p_username text,
  p_password text,
  p_acesso text
)
RETURNS TABLE(id bigint, nome text, username text, acesso text, created_at timestamptz)
LANGUAGE plpgsql AS $$
BEGIN
  IF p_acesso NOT IN ('financeiro','rh','ambos','apenas-observador') THEN
    RAISE EXCEPTION 'acesso_invalido';
  END IF;

  IF EXISTS(SELECT 1 FROM usuarios WHERE username = p_username) THEN
    RAISE EXCEPTION 'username_ja_existe';
  END IF;

  RETURN QUERY
    INSERT INTO usuarios(nome, username, senha, acesso, must_change_password)
    VALUES (p_nome, p_username, crypt(p_password, gen_salt('bf')), p_acesso, true)
    RETURNING id, nome, username, acesso, must_change_password, created_at;
END;
$$;
